"""initial

Revision ID: 08e9070d4da5
Revises: 93e3c2ffc5fd
Create Date: 2026-09-14 08:26:42.285138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08e9070d4da5'
down_revision: Union[str, None] = '93e3c2ffc5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biz_profiles_featured_order'), table_name='biz_profiles')
    op.drop_index(op.f('ix_biz_profiles_is_featured'), table_name='biz_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_biz_profiles_is_featured'), 'biz_profiles', ['is_featured'], unique=False)
    op.create_index(op.f('ix_biz_profiles_featured_order'), 'biz_profiles', ['featured_order'], unique=False)
    # ### end Alembic commands ###
