"""initial

Revision ID: 457f1e2b1376
Revises: d4e5f6a7b8c9
Create Date: 2026-09-09 09:53:15.966214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '457f1e2b1376'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('otps_user_id_fkey'), 'otps', type_='foreignkey')
    op.create_foreign_key(None, 'otps', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('subcategories_category_id_fkey'), 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('subcategories_category_id_fkey'), 'subcategories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'otps', type_='foreignkey')
    op.create_foreign_key(op.f('otps_user_id_fkey'), 'otps', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
