"""initial

Revision ID: 49bc3da35326
Revises: 08e9070d4da5
Create Date: 2026-09-15 10:08:29.819541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49bc3da35326'
down_revision: Union[str, None] = '08e9070d4da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
