"""initial

Revision ID: 5b21d21906b3
Revises: 
Create Date: 2026-09-08 14:48:33.670621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b21d21906b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
