"""initial

Revision ID: 6a7394317a67
Revises: afdcb1be7c00
Create Date: 2026-10-06 10:35:57.292644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a7394317a67'
down_revision: Union[str, None] = 'afdcb1be7c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
