"""initial

Revision ID: 6e3cda87e44c
Revises: b2c3d4e5f6a8
Create Date: 2026-10-02 09:43:56.807798

"""
from typing import Sequence, Union

from alembic import op


revision: str = '6e3cda87e44c'
down_revision: Union[str, None] = 'b2c3d4e5f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# This revision was generated by `alembic revision --autogenerate` without the
# PostGIS filters that now live in alembic/env.py, so the only changes it
# contains are destructive and wrong:
#
#   * DROP TABLE spatial_ref_sys - owned by the postgis extension, which makes
#     the statement fail outright.
#   * DROP COLUMN location on the three geo tables - that column is a GENERATED
#     ALWAYS AS STORED point created by revision b2c3d4e5f6a8. It has no
#     mapped_column() in app/models, so reflection sees it as "in the database
#     but not in the metadata" and autogenerate proposes removing it. Doing so
#     would break every ST_DWithin query in app/repositories/location.py.
#
# There is therefore nothing to do: b2c3d4e5f6a8 already produced the intended
# schema and the models match it.
GEO_TABLES = ("biz_profiles", "biz_services", "service_listings")


def upgrade() -> None:
    return


def downgrade() -> None:
    return
