"""add marketplace tables: products, services, business_hours, favorites, requirements, enquiries, quotations, messages, reviews

Revision ID: 7b7a496170fc
Revises: 43141bbc9b08
Create Date: 2026-09-17 10:39:32.246539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b7a496170fc'
down_revision: Union[str, None] = '43141bbc9b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_favorite_user_target')
    )
    op.create_index('ix_favorites_target', 'favorites', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_is_read', 'messages', ['is_read'], unique=False)
    op.create_index('ix_messages_receiver_id', 'messages', ['receiver_id'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('budget_unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_buyer_id', 'requirements', ['buyer_id'], unique=False)
    op.create_index('ix_requirements_category_id', 'requirements', ['category_id'], unique=False)
    op.create_index('ix_requirements_status', 'requirements', ['status'], unique=False)
    op.create_index('ix_requirements_subcategory_id', 'requirements', ['subcategory_id'], unique=False)
    op.create_table('biz_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['biz_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_biz_services_category_id', 'biz_services', ['category_id'], unique=False)
    op.create_index('ix_biz_services_profile_id', 'biz_services', ['profile_id'], unique=False)
    op.create_index('ix_biz_services_status', 'biz_services', ['status'], unique=False)
    op.create_index('ix_biz_services_subcategory_id', 'biz_services', ['subcategory_id'], unique=False)
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('biz_profile_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['biz_profile_id'], ['biz_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_profile_id', 'day_of_week', name='uq_business_hours_profile_day')
    )
    op.create_index('ix_business_hours_biz_profile_id', 'business_hours', ['biz_profile_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['biz_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_profile_id', 'products', ['profile_id'], unique=False)
    op.create_index('ix_products_slug', 'products', ['slug'], unique=False)
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    op.create_index('ix_products_subcategory_id', 'products', ['subcategory_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['biz_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'profile_id', name='uq_review_buyer_profile')
    )
    op.create_index('ix_reviews_buyer_id', 'reviews', ['buyer_id'], unique=False)
    op.create_index('ix_reviews_profile_id', 'reviews', ['profile_id'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['biz_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['biz_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enquiries_buyer_id', 'enquiries', ['buyer_id'], unique=False)
    op.create_index('ix_enquiries_product_id', 'enquiries', ['product_id'], unique=False)
    op.create_index('ix_enquiries_profile_id', 'enquiries', ['profile_id'], unique=False)
    op.create_index('ix_enquiries_requirement_id', 'enquiries', ['requirement_id'], unique=False)
    op.create_index('ix_enquiries_service_id', 'enquiries', ['service_id'], unique=False)
    op.create_index('ix_enquiries_status', 'enquiries', ['status'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotations_buyer_id', 'quotations', ['buyer_id'], unique=False)
    op.create_index('ix_quotations_enquiry_id', 'quotations', ['enquiry_id'], unique=False)
    op.create_index('ix_quotations_seller_id', 'quotations', ['seller_id'], unique=False)
    op.create_index('ix_quotations_status', 'quotations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotations_status', table_name='quotations')
    op.drop_index('ix_quotations_seller_id', table_name='quotations')
    op.drop_index('ix_quotations_enquiry_id', table_name='quotations')
    op.drop_index('ix_quotations_buyer_id', table_name='quotations')
    op.drop_table('quotations')
    op.drop_index('ix_product_images_product_id', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_enquiries_status', table_name='enquiries')
    op.drop_index('ix_enquiries_service_id', table_name='enquiries')
    op.drop_index('ix_enquiries_requirement_id', table_name='enquiries')
    op.drop_index('ix_enquiries_profile_id', table_name='enquiries')
    op.drop_index('ix_enquiries_product_id', table_name='enquiries')
    op.drop_index('ix_enquiries_buyer_id', table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_profile_id', table_name='reviews')
    op.drop_index('ix_reviews_buyer_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_products_subcategory_id', table_name='products')
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index('ix_products_slug', table_name='products')
    op.drop_index('ix_products_profile_id', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_business_hours_biz_profile_id', table_name='business_hours')
    op.drop_table('business_hours')
    op.drop_index('ix_biz_services_subcategory_id', table_name='biz_services')
    op.drop_index('ix_biz_services_status', table_name='biz_services')
    op.drop_index('ix_biz_services_profile_id', table_name='biz_services')
    op.drop_index('ix_biz_services_category_id', table_name='biz_services')
    op.drop_table('biz_services')
    op.drop_index('ix_requirements_subcategory_id', table_name='requirements')
    op.drop_index('ix_requirements_status', table_name='requirements')
    op.drop_index('ix_requirements_category_id', table_name='requirements')
    op.drop_index('ix_requirements_buyer_id', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_receiver_id', table_name='messages')
    op.drop_index('ix_messages_is_read', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_favorites_user_id', table_name='favorites')
    op.drop_index('ix_favorites_target', table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
