"""initial

Revision ID: 93e3c2ffc5fd
Revises: j3k4l5m6n7o8
Create Date: 2026-09-14 08:24:22.099943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93e3c2ffc5fd'
down_revision: Union[str, None] = 'j3k4l5m6n7o8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biz_profiles_featured_order'), table_name='biz_profiles')
    op.drop_index(op.f('ix_biz_profiles_is_featured'), table_name='biz_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_biz_profiles_is_featured'), 'biz_profiles', ['is_featured'], unique=False)
    op.create_index(op.f('ix_biz_profiles_featured_order'), 'biz_profiles', ['featured_order'], unique=False)
    # ### end Alembic commands ###
