"""initial

Revision ID: 9df2217ef0cc
Revises: 7b743588cef1
Create Date: 2026-09-30 09:27:25.273814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9df2217ef0cc'
down_revision: Union[str, None] = '7b743588cef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
