"""initial

Revision ID: afdcb1be7c00
Revises: ae5a89e4a5d6
Create Date: 2026-10-05 15:35:34.150249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'afdcb1be7c00'
down_revision: Union[str, None] = 'ae5a89e4a5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
