"""initial

Revision ID: d8679aae8bc3
Revises: 6a7394317a67
Create Date: 2026-10-06 13:31:01.746350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd8679aae8bc3'
down_revision: Union[str, None] = '6a7394317a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
